/* uquest.init_jquery.js */
"(function() {\n    function onload(){\n        EBCallBackMessageReceived('jquery_initialized');\n    };\n\n    if (!window.jQuery) {\n        var src = '//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js';\n        var script = document.createElement('script');\n        script.type = 'text/javascript';\n        //---start IE fix---\n        if(window.ActiveXObject){//ie fix T_T\n            var xmlhttp = null;\n            try {\n                xmlhttp = new XMLHttpRequest();\n            }catch(e){\n                try{\n                    xmlhttp = new ActiveXObject('Msxml2.XMLHTTP');\n                }catch(e){\n                    xmlhttp = new ActiveXObject('Microsoft.XMLHTTP');\n                }\n            }\n            xmlhttp.onreadystatechange  = function() {\n                try{\n                    if(this.done!==undefined)\n                        return;\n\n                    if(this.status >= 200 && this.status < 300){//loaded\n                        this.done=true;\n                        script.text=this.responseText;\n                        document.getElementsByTagName('head')[0].appendChild(script);\n                        onload();\n                    }\n                    if(this.status >= 400){\n                        this.done=true;\n                    }\n                } catch(e) {}\n            };\n            xmlhttp.open('get', src, true);\n            xmlhttp.send(null);\n\n        }\n        else{//browser that support script.onload/onerror\n            script.src = src;\n            script.async = true;\n            script.onload = onload;\n            document.getElementsByTagName('head')[0].appendChild(script);\n        }\n        //---end IE fix---\n    }\n}());"

/* uquest.inject.js */
"(function () {\n    window.QuestModule = {\n        _is_active : true,\n        _selector : 'a',\n        init : function() {\n            /*TODO use jquery. At the moment jQuery may not be initialized here*/\n            /*TODO url path from config*/\n            var el = document.createElement('link');\n            el.setAttribute('type', 'text/css');\n            el.setAttribute('rel', 'stylesheet');\n            el.setAttribute('href', 'http://localhost/toolbar2/css/style_inject.css');\n            document.getElementsByTagName('head')[0].appendChild(el);\n/*          el.setAttribute('type', 'text/css');\n            el.innerHTML = '.utorrent-uquest-inject { background-color: yellow };';\n*/\n        },\n        set_state : function(active) {\n            this._is_active = active;\n            if(this._is_active){\n                jQuery(this._selector).each(function(){\n                    var span = jQuery('<span>').addClass('utorrent-uquest-span').attr('title', 'Download torrent');\n                    jQuery(this).addClass('utorrent-uquest-inject').append(span);\n                })\n            } else {\n                jQuery(this._selector).each(function(){\n                    jQuery(this).removeClass('utorrent-uquest-inject').children('.utorrent-uquest-span').remove();\n                })\n            }\n        }\n    };\n\n    window.QuestModule.init();\n}());"

/* uquest.inject.setactive.js */
"(function () {\n    window.QuestModule.set_state(true);\n}());"

/* uquest.inject.setinactive.js */
"(function () {\n    window.QuestModule.set_state(false);\n}());"

